name: dotnet-pipeline

on : 
  push : 
    branches :
      - develop

jobs : 
  dotnet-build :
    runs-on : 'ubuntu-latest'

    steps : 
      - name : Checkout code 
        uses : actions/cache@v4


      - name: sonarscan
        uses: sonarsource/sonarcloud-github-action@v3
        with: 
          sonartoken: ${{ secrets.SONAR_TOKEN }}
          sonarURL: ${{ secrets.SONAR_URL }}
          project_key: ${{ secrets.PROJECT_KEY }}
          organization_key: ${{ secrets.ORGANIZATION_KEY }}

      - name: setup dotnet
        uses: actions/setup-dotnet@v4
        with : 
          dotnet-version: '9.0.100' 

      - name : dotnet build 
        run: |
          dotnet publish -c Release src/Presentation/Nop.Web/Nop.Web.csproj -o demo